# This file is generated by the release workflow of wakaka6/just-talk-go.
# Do not edit by hand in the tap repository.
class JustTalk < Formula
  desc "Desktop voice input: global hotkey, streaming ASR, paste into the focused field"
  homepage "https://github.com/wakaka6/just-talk-go"
  license "GPL-3.0-only"

  # The archives wrap the binary in a just-talk_<os>_<arch>/ directory.
  on_macos do
    on_arm do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.2.0/just-talk_darwin_arm64.tar.gz"
      sha256 "eb58c8f0d2a7eeeba032d1a1b6132eacd92cd9e3abcd8840f83c78f01b07c3b1"
    end

    on_intel do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.2.0/just-talk_darwin_amd64.tar.gz"
      sha256 "f0798098614783ebd5a79d3f94d2f0cb94d20246a5669bc5cc4c61534fd03037"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.2.0/just-talk_linux_arm64.tar.gz"
      sha256 "8ad1a517b602811aca04e5ac695feb603573a56aa69ae11fea0eb30e2fa6f11b"
    end

    on_intel do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.2.0/just-talk_linux_amd64.tar.gz"
      sha256 "42487b0185ecd40bebf707093729c23bee290d05d69ada8766b8f9012d6ff106"
    end

    # The cgo build links these X11/Wayland libraries at runtime.
    depends_on "libx11"
    depends_on "libxext"
    depends_on "libxinerama"
    depends_on "libxrender"
    depends_on "libxtst"
    depends_on "wayland"
  end

  def install
    bin.install Dir.glob("just-talk_*/just-talk").first || "just-talk"
  end

  def caveats
    if OS.mac?
      <<~EOS
        just-talk needs permission granted to the terminal app that launches it
        (Terminal, iTerm2, etc.):

          * Accessibility: System Settings > Privacy & Security > Accessibility
          * Microphone:    System Settings > Privacy & Security > Microphone

        Configure your Doubao/Volcengine ASR credentials in
        ~/.config/just-talk/config.toml ([voice] app_key / access_key) or via the TUI.
      EOS
    else
      <<~EOS
        just-talk needs a running X11 or Wayland session ($DISPLAY or
        $WAYLAND_DISPLAY); global hotkeys may also need compositor/portal
        permission depending on your desktop environment.

        Configure your Doubao/Volcengine ASR credentials in
        ~/.config/just-talk/config.toml ([voice] app_key / access_key) or via the TUI.
      EOS
    end
  end

  test do
    # There is no --version flag; --help proves the binary runs (flag package exits 0).
    assert_match "Usage of", shell_output("#{bin}/just-talk --help 2>&1")
  end
end
