# This file is generated by the release workflow of wakaka6/just-talk-go.
# Do not edit by hand in the tap repository.
class JustTalk < Formula
  desc "Desktop voice input: global hotkey, streaming ASR, paste into the focused field"
  homepage "https://github.com/wakaka6/just-talk-go"
  license "GPL-3.0-only"

  # The archives wrap the binary in a just-talk_<os>_<arch>/ directory.
  on_macos do
    on_arm do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.1.0/just-talk_darwin_arm64.tar.gz"
      sha256 "aad0dad68a118f7d33126632e15aca17165d4acb419ef41b106e6657773edc47"
    end

    on_intel do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.1.0/just-talk_darwin_amd64.tar.gz"
      sha256 "0397c4ca8c7173d5d9e0845340f2f79576c275e586476c3d5579abfc368a5da1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.1.0/just-talk_linux_arm64.tar.gz"
      sha256 "17b933613a0e09b6937e76fc8b0af40b5a7fb53a94f5afd0ab95cc1c953156d2"
    end

    on_intel do
      url "https://github.com/wakaka6/just-talk-go/releases/download/v0.1.0/just-talk_linux_amd64.tar.gz"
      sha256 "e2327b3c680d3b3165d71666c0a21887074a28aaaa9bbdd71a74af9ee4a40eae"
    end

    # The cgo build links these X11/Wayland libraries at runtime.
    depends_on "libx11"
    depends_on "libxext"
    depends_on "libxinerama"
    depends_on "libxrender"
    depends_on "libxtst"
    depends_on "wayland"
  end

  def install
    bin.install Dir.glob("just-talk_*/just-talk").first || "just-talk"
  end

  def caveats
    if OS.mac?
      <<~EOS
        just-talk needs permission granted to the terminal app that launches it
        (Terminal, iTerm2, etc.):

          * Accessibility: System Settings > Privacy & Security > Accessibility
          * Microphone:    System Settings > Privacy & Security > Microphone

        Configure your Doubao/Volcengine ASR credentials in
        ~/.config/just-talk/config.toml ([voice] app_key / access_key) or via the TUI.
      EOS
    else
      <<~EOS
        just-talk needs a running X11 or Wayland session ($DISPLAY or
        $WAYLAND_DISPLAY); global hotkeys may also need compositor/portal
        permission depending on your desktop environment.

        Configure your Doubao/Volcengine ASR credentials in
        ~/.config/just-talk/config.toml ([voice] app_key / access_key) or via the TUI.
      EOS
    end
  end

  test do
    # There is no --version flag; --help proves the binary runs (flag package exits 0).
    assert_match "Usage of", shell_output("#{bin}/just-talk --help 2>&1")
  end
end
